const NAME_TO_ISO2: Record<string, string> = {
  pl: "pl",
  polska: "pl",
  poland: "pl",
  de: "de",
  niemcy: "de",
  germany: "de",
  deutschland: "de",
  fr: "fr",
  francja: "fr",
  france: "fr",
  es: "es",
  hiszpania: "es",
  spain: "es",
  it: "it",
  wlochy: "it",
  włochy: "it",
  italy: "it",
  italia: "it",
  cz: "cz",
  czechy: "cz",
  czechia: "cz",
  "czech republic": "cz",
  sk: "sk",
  slowacja: "sk",
  slovakia: "sk",
  at: "at",
  austria: "at",
  be: "be",
  belgia: "be",
  belgium: "be",
  nl: "nl",
  holandia: "nl",
  niderlandy: "nl",
  netherlands: "nl",
  se: "se",
  szwecja: "se",
  sweden: "se",
  no: "no",
  norwegia: "no",
  norway: "no",
  dk: "dk",
  dania: "dk",
  denmark: "dk",
  fi: "fi",
  finlandia: "fi",
  finland: "fi",
  pt: "pt",
  portugalia: "pt",
  portugal: "pt",
  gr: "gr",
  grecja: "gr",
  greece: "gr",
  hu: "hu",
  wegry: "hu",
  węgry: "hu",
  hungary: "hu",
  ro: "ro",
  rumunia: "ro",
  romania: "ro",
  ua: "ua",
  ukraina: "ua",
  ukraine: "ua",
  gb: "gb",
  uk: "gb",
  "united kingdom": "gb",
  anglia: "gb",
  "wielka brytania": "gb",
  "great britain": "gb",
  ireland: "ie",
  irlandia: "ie",
  ie: "ie",
  ch: "ch",
  szwajcaria: "ch",
  switzerland: "ch",
  hr: "hr",
  chorwacja: "hr",
  croatia: "hr",
  si: "si",
  slowenia: "si",
  slovenia: "si",
  rs: "rs",
  serbia: "rs",
  bg: "bg",
  bulgaria: "bg",
  bułgaria: "bg",
  lt: "lt",
  litwa: "lt",
  lv: "lv",
  lotwa: "lv",
  ee: "ee",
  estonia: "ee",
};

export function resolveCountryCodesParam(country: string): string | undefined {
  const raw = country.trim();
  if (!raw) return undefined;
  const k = raw.toLowerCase();
  if (k.length === 2 && /^[a-z]{2}$/i.test(k)) return k.toLowerCase();
  if (k.includes("wielka bryt") || k.includes("great britain")) return "gb";
  return NAME_TO_ISO2[k];
}
